name: screenshots
description: Auto-generation of screenshots for Apple and Play Stores using emulators, simulators and real devices. Includes support for multiple locales and framing. Compatible with fastlane.
version: 2.3.2
homepage: https://github.com/DrBu7cher/screenshots
publish_to: none

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  archive: ^3.6.1
  args: ^2.5.0
  file: ^7.0.0
  http: any
  meta: any
  path: ^1.9.0
  platform: any
  process: ^5.0.2
  resource_portable: ^3.0.0
  # network_info_plus: "^3.0.3"
  tool_mobile:
    git:
      url: https://github.com/jonasbadstuebner/tool_mobile.git
#      ref: 777a3ed6943331b925581484f689ce28576f22f1
    # path: /home/jbadstuebner/Dokumente/git/github.com/DrBu7cher/tool_mobile/main
  yaml: "^3.1.0"

dev_dependencies:
  fake_process_manager:
    git:
      url: https://github.com/jonasbadstuebner/fake_process_manager.git
#      ref: 3a877ee22b8497b6be616738e32a14c0ae7abb3a

    # path: /home/jbadstuebner/Dokumente/git/github.com/DrBu7cher/fake_process_manager/main
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  quiver: ^3.2.1
  tool_base_test:
    git:
      url:  https://github.com/jonasbadstuebner/tool_base_test.git
#      ref: 6e801f03e56dd34d42ba779e9a76755ec84ec394
    # path: /home/jbadstuebner/Dokumente/git/github.com/DrBu7cher/tool_base_test/main

dependency_overrides:
  tool_base:
    git:
      url: https://github.com/graux/tool_base.git

executables:
  screenshots: main
